database:
  type: mysql
  driver: pymysql
  username: your_username
  password: your_password
  host: your_host
  port: your_port
  database_name: your_database

MLFLOW_TRACKING_URI: 'http://your_mlflow_server:5000'
SECRET_KEY: 'your_secret_key'
